config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get "bebidas", to: "bebidas#index"
  get "bebidas/new", to: "bebidas#new"
  post "bebidas", to: "bebidas#create"
  get "bebidas/:id/edit", to: "bebidas#edit", as: :edit_bebidas
  patch "bebidas/:id", to:"bebidas#update"
  delete "bebidas/:id/", to: "bebidas#destroy", as: :bebida
  delete 'sessions/new', to:'sessions#destroy', as: :logout
  get 'sessions/new', to: 'sessions#new', as: :authentication_form
  post 'sessions', to: 'sessions#create', as: :authentication
  get "burguers", to: "burguers#index"
  get "burguers/new", to: "burguers#new"
  post "burguers", to: "burguers#create"
  get "burguers/:id/edit", to: "burguers#edit", as: :edit_burguers
  patch "burguers/:id", to:"burguers#update"
  delete "burguers/:id/", to: "burguers#destroy", as: :burguer
  get "contratos", to: "contratos#index"
  get "contratos/new", to: "contratos#new"
  post "contratos", to: "contratos#create"
  get "contratos/:id/edit", to: "contratos#edit", as: :edit_contratos
  patch "contratos/:id", to:"contratos#update", as: :contrato
  delete "contratos/:id/", to: "contratos#destroy", as: :contratinho
  get "cardapios", to: "cardapios#index", as: :cardapinho
end

app/models/admin.rb
class Admin < ApplicationRecord
    has_secure_password
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bebida.rb
class Bebida < ApplicationRecord
    validates  :descricao , :presence => { :message => " é obrigatório !"}  
    validates  :valor , :presence => { :message => " é obrigatório !"} 
end

app/models/burguer.rb
class Burguer < ApplicationRecord
    validates  :nome , :presence => { :message => " é obrigatório !"}  
    validates  :descricao , :presence => { :message => " é obrigatório !"}  
    validates  :valor , :presence => { :message => " é obrigatório !"} 
end

app/models/contrato.rb
class Contrato < ApplicationRecord
  belongs_to :burguer, optional: true
  belongs_to :bebida, optional: true
  validates  :nome , :presence => { :message => " é obrigatório !"}  
  validates  :telefone , :presence => { :message => " é obrigatório !"}  
  validates  :endereco , :presence => { :message => " é obrigatório !"} 
  validates  :burguer , :presence => { :message => " é obrigatório !"}  
  
  validate :validar_telefone 
  def validar_telefone
    return if telefone.blank?
    if telefone.count('0123456789') != 11 || telefone.size != 11
      errors.add(:telefone, "Invalido")
    end  
  end  

  def valor
    burguer.valor + bebida.valor
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :require_authentication

    def require_authentication
        if !session[:admin_id]
            redirect_to authentication_form_path
        end
    end 
end

app/controllers/bebidas_controller.rb
class BebidasController < ApplicationController
    skip_before_action :verify_authenticity_token, :require_authentication, only: [:create]
    def index
        @bebidas = Bebida.order(descricao: :asc)
    end

    def create
        attrs = params.require(:bebida).permit(:descricao, :valor)
        @bebida = Bebida.new attrs
        
        if @bebida.save
        flash[:notice] = "Bebida cadastrada com sucesso"
        redirect_to bebidas_path  
        else
        render :new
        end  
    end  
    def new
        @bebida = Bebida.new
    end 
    def update
        @bebida = Bebida.find(params[:id])
        if @bebida.update(descricao: params[:bebida][:descricao], valor: params[:bebida][:valor])
            redirect_to bebidas_path
        else 
            render :edit
        end     
    end
    def destroy
        id = params[:id]
        Bebida.destroy id
        redirect_to bebidas_path
    end  
    def edit
        @bebida = Bebida.find(params[:id])
    end
end    

app/controllers/burguers_controller.rb
class BurguersController < ApplicationController
    def index
        @burguers = Burguer.order(nome: :asc)
    end    

    def create
        attrs = params.require(:burguer).permit(:nome, :descricao, :valor)
        @burguer = Burguer.new attrs
        
        if @burguer.save
        flash[:notice] = "Lanche cadastrado com sucesso"
        redirect_to burguers_path  
        else
        render :new
        end  
    end  
    def new
        @burguer = Burguer.new
    end 
    def update
        @burguer = Burguer.find(params[:id])
        if @burguer.update(nome: params[:burguer][:nome], descricao: params[:burguer][:descricao], valor: params[:burguer][:valor])
            redirect_to burguers_path
        else 
            render :edit
        end     
    end
    def destroy
        id = params[:id]
        Burguer.destroy id
        redirect_to burguers_path
    end  
    def edit
        @burguer = Burguer.find(params[:id])
    end
end    

app/controllers/cardapios_controller.rb
class CardapiosController < ApplicationController
    skip_before_action :require_authentication
    def index
    end
end    

app/controllers/contratos_controller.rb
class ContratosController < ApplicationController
    skip_before_action :require_authentication
    def index 
        @contratos = Contrato.order(created_at: :desc)
        @valor_recebido = 0
        @contratos.each do |contrato|
            @valor_recebido = @valor_recebido + contrato.valor
        end
    end
    
    def create
        attrs = params.require(:contrato).permit(:nome, :telefone, :endereco, :burguer_id, :bebida_id)
        @contrato = Contrato.new attrs
        if @contrato.save
            redirect_to contratos_path
            flash[:notice] = "Pedido realizado com sucesso"
        else 
            render :new
        end
    end 

    def new
        @contrato = Contrato.new
    end    

    def edit
        @contrato = Contrato.find(params[:id])
    end

    def update
        @contrato = Contrato.find(params[:id])
        if @contrato.update(nome: params[:contrato][:nome], telefone: params[:contrato][:telefone], endereco: params[:contrato][:endereco], burguer_id: params[:contrato][:burguer_id], bebida_id: params[:contrato][:bebida_id])
            redirect_to contratos_path
        else 
            render :edit
        end     
    end

    def destroy
        id = params[:id]
        Contrato.destroy id
        redirect_to contratos_path
    end 



    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    skip_before_action :require_authentication
    def index
    end
end    

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_authentication
    layout "login"
  
    def new
      
    end
  
    def create
      @admin = Admin.find_by(username: params[:session][:username])
      if @admin && @admin.authenticate(params[:session][:password])
        session[:admin_id] = @admin.id
        redirect_to(root_path)
      else
        flash[:alert] = "Usuario e/ou senha invalido(s)"
        redirect_to authentication_form_path
      end
    end  
  
    def destroy       
      session[:admin_id] = nil   
      p session[:admin_id]  
      redirect_to authentication_form_path
    end 
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bebidas/_form.html.erb
    <% @bebida.errors.full_messages.each do |msg| %>
    <div class="alert alert-danger" role="alert">
        <%= msg %>
    </div>
<% end %>
<%= form_for @bebida  do |form|%>
    <div class="container mx-auto border mt-3" style="background-color: #FFE4C4; border-color: #000000 !important;">
        <div class="row mt-5">
            <div  class="col-sm-5 mx-auto">
                <div class="form-group"  >
                    <%= form.label :descricao%>
                    <%= form.text_field :descricao, class:"form-control mb-2 mt-2", style: "border-color: #000000; resize: none "%>
                </div>
            </div>
        </div>   
        <div class="row">
            <div class="col-sm-5 mx-auto" >
                <div class="form-group">
                    <%= form.label :valor%>
                    <%= form.text_field :valor,  class:"form-control mb-2 mt-2", style: "border-color: #000000; resize:none"%>
                </div>
            </div>
        </div>       
        <div class="row mt-3">
            <div class="col-md-5 mb-4 mx-auto">
              <%= form.submit "Salvar", class:"btn btn-lg  text-white ", style: "background-color: #A0522D" %>
               <%=link_to "Cancelar", bebidas_path, class: "btn  btn-lg btn-danger text-white"%>
            </div>
        </div> 
    </div>    
<% end %>

app/views/bebidas/edit.html.erb
<html>
<body>
<div class="container">
<div style="background-color: #A0522D">
<h3 style="color:#FFE4C4" class="mt-5 text-center"><i style="color: red;" class="fas fa-cocktail mt-2 fa-2x"></i>Editar Bebida</h3>
<%= render "form"%>
</div>
</div>

</html>
</body>

app/views/bebidas/index.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success" role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>
<div class="container mt-5">
<h3 class="text-center mb-4">Bebidas</h3>



<table class="table table-bordered table-hover text-center" style="border-color:#000000 ">
    <thead>
        <tr>
            <td class="text-white" style="word-wrap: break-word; !important; background-color: #F4A460">Descrição</td>
            <td class="text-white" style="word-wrap: break-word; !important; background-color: #F4A460;">Valor</td>
            <td class="text-white" style="word-wrap: break-word; !important; background-color: #F4A460;">Ações</td>
        </tr>
    </thead>
    <tbody>
    <% @bebidas.each do |bebida| %>
        <tr>
            <td><%= bebida.descricao %></td>
            <td><%= bebida.valor %></td>
            <td><%=link_to "Editar", edit_bebidas_path(bebida.id), class: "btn btn-info text-white", style: "background-color: #A0522D"%>
            <%= link_to "Remover", bebida, method: :delete, data: {confirm:"Tem certeza que deseja remover a bebida: #{bebida.descricao}?"}, class: "btn btn-danger text-white"  %></td>
        </tr>
    <% end %>
    </tbody>
</table> 
</div>

app/views/bebidas/new.html.erb
<html>
<body>
<div class="container">
<div style="background-color: #A0522D">
<h3 style="color:#FFE4C4" class="mt-5 text-center"><i style="color: red;" class="fas fa-cocktail mt-2 fa-2x"></i>Cadastrar Bebida</h3>
<%= render "form"%>
</div>
</div>

</html>
</body>

app/views/burguers/_form.html.erb
    <% @burguer.errors.full_messages.each do |msg| %>
    <div class="alert alert-danger" role="alert">
        <%= msg %>
    </div>
<% end %>
<%= form_for @burguer  do |form|%>
    <div class="container mx-auto border mt-3" style="background-color: #FFE4C4; border-color: #000000 !important;">
        <div class="row mt-5">
            <div  class="col-sm-5 mx-auto">
                <div class="form-group"  >
                    <%= form.label :nome%>
                    <%= form.text_field :nome, class:"form-control mb-2 mt-2", style: "border-color: #000000; resize: none "%>
                </div>
            </div>
        </div> 
        <div class="row">
            <div  class="col-sm-5 mx-auto">
                <div class="form-group"  >
                    <%= form.label :descricao%>
                    <%= form.text_field :descricao, class:"form-control mb-2 mt-2", style: "border-color: #000000; resize: none "%>
                </div>
            </div>
        </div>   
        <div class="row">
            <div class="col-sm-5 mx-auto" >
                <div class="form-group">
                    <%= form.label :valor%>
                    <%= form.text_field :valor,  class:"form-control mb-2 mt-2", style: "border-color: #000000; resize:none"%>
                </div>
            </div>
        </div>       
        <div class="row mt-3">
            <div class="col-md-5 mb-4 mx-auto">
              <%= form.submit "Salvar", class:"btn btn-lg  text-white ", style: "background-color: #A0522D" %>
               <%=link_to "Cancelar", burguers_path, class: "btn  btn-lg btn-danger text-white"%>
            </div>
        </div> 
    </div>    
<% end %>

app/views/burguers/edit.html.erb
<html>
<body>
<div class="container">
<div style="background-color: #A0522D">
<h3 style="color:#FFE4C4" class="mt-5 text-center"><i style="color: #FFE4C4" class="fas fa-hamburger fa-2x"></i> Editar Lanche</h3>
<%= render "form"%>
</div>
</div>

</html>
</body>

app/views/burguers/index.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success" role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>
<div class="container mt-5">
<h3 class="text-center mb-4">Lanches</h3>

<table class="table table-bordered table-hover text-center" style="border-color:#000000 ">
    <thead>
        <tr>
            <td class="text-white" style="word-wrap: break-word; !important; background-color: #F4A460">Nome</td>
            <td class="text-white" style="word-wrap: break-word; !important; background-color: #F4A460">Descrição</td>
            <td class="text-white" style="word-wrap: break-word; !important; background-color: #F4A460;">Valor</td>
            <td class="text-white" style="word-wrap: break-word; !important; background-color: #F4A460;">Ações</td>
        </tr>
    </thead>
    <tbody>
    <% @burguers.each do |burguer| %>
        <tr>
            <td><%= burguer.nome %></td>
            <td><%= burguer.descricao %></td>
            <td><%= burguer.valor %></td>
            <td><%=link_to "Editar", edit_burguers_path(burguer.id), class: "btn text-white", style: "background-color: #A0522D"%>
            <%= link_to "Remover", burguer, method: :delete, data: {confirm:"Tem certeza que deseja remover a bebida: #{burguer.nome}?"}, class: "btn btn-danger text-white"  %></td>
        </tr>
    <% end %>
    </tbody>
</table> 
</div>

app/views/burguers/new.html.erb
<html>
<body>
<div class="container">
<div style="background-color: #A0522D">
<h3 style="color:#FFE4C4" class="mt-5 text-center"><i style="color: #FFE4C4" class="fas fa-hamburger mt-2 fa-2x"></i> Cadastrar Lanche</h3>
<%= render "form"%>
</div>
</div>
</html>
</body>

app/views/cardapios/index.html.erb
<html>
<body style="background-color: #FFE4C4">
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3 class="text-center mt-5">Cárdapio</h3>
        </div>
        <div class="col-md-3">
            <div class="text-center p-o">
                <div class="card border-0" style="width: 18rem;">
                    <img  src="https://offloadmedia.feverup.com/saopaulosecreto.com/wp-content/uploads/2021/01/08043605/pexels-caleb-oquendo-3023479-1024x683.jpg" class="card-img-top" alt="...">
                    <div class="card-body" style="background-color: #BC8F8F;">
                        <h5 class="card-title text-white">Hot Dog</h5>
                        <p class="card-text text-white">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    </div>
                </div>
            </div>    
        </div>
        <div class="col-md-3">
            <div class="text-center p-o">
                <div class="card border-0" style="width: 18rem;">
                    <img src="https://static5.depositphotos.com/1000647/467/i/600/depositphotos_4674723-stock-photo-tasty-and-appetizing-hamburger-on.jpg" class="card-img-top" alt="...">
                    <div class="card-body text-white" style="background-color: #BC8F8F;">
                        <h5 class="card-title text-white">Big Burguer</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    </div>
                </div>
            </div>    
        </div>
         <div class="col-md-3">
            <div class="text-center">
                <div class="card border-0" style="width: 18rem;">
                    <img src="https://p4.wallpaperbetter.com/wallpaper/209/721/107/food-burger-wallpaper-preview.jpg" class="card-img-top" alt="...">
                    <div class="card-body text-white" style="background-color: #BC8F8F;">
                        <h5 class="card-title">Card title</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    </div>
                </div>
            </div>    
        </div>
        <div class="col-md-3">
            <div class="text-center">
                <div class="card border-0" style="width: 18rem;">
                    <img src="https://img.freepik.com/vetores-gratis/hamburguer-realista-no-fundo-do-quadro_79603-1042.jpg?size=626&ext=jpg" class="card-img-top" alt="...">
                    <div class="card-body text-white" style="background-color: #BC8F8F;">
                        <h5 class="card-title">Card title</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    </div>
                </div>
            </div>    
        </div>

        <div class="col-md-3">
            <div class="text-center p-o">
                <div class="card border-0" style="width: 18rem;">
                    <img  src="https://images8.alphacoders.com/457/457153.jpg" class="card-img-top" alt="...">
                    <div class="card-body" style="background-color: #BC8F8F;">
                        <h5 class="card-title text-white">Sucos</h5>
                        <p class="card-text text-white">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    </div>
                </div>
            </div>    
        </div>
        <div class="col-md-3">
            <div class="text-center p-o">
                <div class="card border-0" style="width: 18rem;">
                    <img src="https://images5.alphacoders.com/293/293049.jpg" class="card-img-top" alt="...">
                    <div class="card-body text-white" style="background-color: #BC8F8F;">
                        <h5 class="card-title text-white">Cervejas</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    </div>
                </div>
            </div>    
        </div>
         <div class="col-md-3">
            <div class="text-center">
                <div class="card border-0" style="width: 18rem;">
                    <img src="https://images5.alphacoders.com/406/thumb-1920-406996.jpg" class="card-img-top" alt="...">
                    <div class="card-body text-white" style="background-color: #BC8F8F;">
                        <h5 class="card-title">Refrigerantes</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    </div>
                </div>
            </div>    
        </div>
        <div class="col-md-3 mb-5">
            <div class="text-center">
                <div class="card border-0" style="width: 18rem;">
                    <img src="https://images6.alphacoders.com/304/thumb-1920-304536.jpg" class="card-img-top" alt="...">
                    <div class="card-body text-white" style="background-color: #BC8F8F;">
                        <h5 class="card-title">Drinks</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    </div>
                </div>
            </div>    
        </div>
    </div>
</div>
</html>
</body>

app/views/contratos/_form.html.erb
<% @contrato.errors.full_messages.each do |msg| %>
    <div class="alert alert-danger" role="alert">
        <%= msg %>
    </div>
<% end %>
<%= form_for @contrato  do |form|%>
    <div class="container mx-auto border mt-3" style="background-color: #FFE4C4; border-color: #000000 !important">
        <div class="row">
            <div  class="col-md-5 mt-5 mx-auto">
                <div class="form-group"  >
                    <%= form.label :nome%>
                    <%= form.text_field :nome, class:"form-control mb-2 mt-2", style: "border-color: #000000; resize: none "%>
                </div>
            </div>
            <div  class="col-md-5 mt-5 mx-auto">
                <div class="form-group"  >
                    <%= form.label :telefone%>
                    <%= form.text_field :telefone, class:"form-control mb-2 mt-2", style: "border-color: #000000; resize: none "%>
                </div>
            </div>
        </div>  
         <div class="row">
            <div  class="col-md-5 mx-auto">
                <div class="form-group"  >
                    <%= form.label :endereco%>
                    <%= form.text_field :endereco, class:"form-control  mt-2", style: "border-color: #000000; resize: none "%>
                </div>
            </div>
            <div  class="col-md-5 mx-auto">
                <div class="form-group">
                    <%= form.label :burguer_id%>  
                </div>
                <%= form.select :burguer_id, Burguer.all.pluck(:nome, :id) ,{prompt: "Escolha o seu Lanche"}, class:"form-select mt-2", style: "border-color: #000000; resize: none "%>
                </select>
            </div>
        </div>     
        <div class="row">
            <div  class="col-md-5 mx-auto">
                <div class="form-group"  >
                    <%= form.label :bebida_id, class:"mt-2 mb-2" %>  
                </div>    
                 <%= form.select :bebida_id, Bebida.all.pluck(:descricao, :id), {prompt: "Escolha a sua Bebida"} ,class:"form-select", style: "border-color: #000000; resize: none "%>     
            </div>    
            <div  class="col-md-5 mx-auto"></div>
        </div>    
        <div class="row mt-3">
            <div class= "col-md-5"></div>
            <div class="col-md-5 mb-4 text-end">
              <%= form.submit "Salvar", class:"btn btn-lg  text-white ", style: "background-color: #A0522D" %>
               <%=link_to "Cancelar", cardapinho_path, class: "btn  btn-lg btn-danger text-white"%>
            </div>
        </div> 
    </div>    
<% end %>

app/views/contratos/edit.html.erb
<html>
<body>
<div class="container">
<div style="background-color: #A0522D">
<h3 style="color:#FFE4C4" class="mt-5 text-center"><i style="color: #FFE4C4" class="fas fa-hamburger fa-2x"></i> Alterar Pedido</h3>
<%= render "form"%>
</div>
</div>

</html>
</body>

app/views/contratos/index.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success" role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>
<div class="container mt-5">
<h3 class="text-center mb-4">Pedidos</h3>

<h4 style="color: #A0522D">Valor Recebido dos Pedidos: R$<%= @valor_recebido %> </h4>

<table class="table table-bordered table-hover text-center" style="border-color:#000000 ">
    <thead>
        <tr>
            <td class="text-white" style="word-wrap: break-word; !important; background-color: #F4A460">Nome</td>
            <td class="text-white" style="word-wrap: break-word; !important; background-color: #F4A460">Endereco</td>
            <td class="text-white" style="word-wrap: break-word; !important; background-color: #F4A460;">Telefone</td>
            <td class="text-white" style="word-wrap: break-word; !important; background-color: #F4A460;">Lanche</td>
            <td class="text-white" style="word-wrap: break-word; !important; background-color: #F4A460;">Bebida</td>
            <td class="text-white" style="word-wrap: break-word; !important; background-color: #F4A460;">Valor</td>
             <td class="text-white" style="word-wrap: break-word; !important; background-color: #F4A460;">Ações</td>
        </tr>
    </thead>
    <tbody>
    <% @contratos.each do |contrato| %>
        <tr>
            <td><%= contrato.nome %></td>
            <td><%= contrato.endereco %></td>
            <td><%= contrato.telefone %></td>
            <td><%= contrato.burguer.nome %></td>
            <td><%= contrato.bebida.descricao %></td>
            <td><%= contrato.valor %></td>
            <td><%=link_to "Editar", edit_contratos_path(contrato.id) , class: "btn text-white", style: "background-color: #A0522D"%>
             <%= link_to "Remover", contrato, method: :delete, data: {confirm:"Tem certeza que deseja remover o pedido de: #{contrato.nome}?"}, class: "btn btn-danger text-white"  %></td>
        </tr>
    <% end %>
    </tbody>
</table> 
</div>

app/views/contratos/new.html.erb
<html>
<body>
<div class="container">
<div style="background-color: #A0522D">
<h3 style="color:#FFE4C4" class="mt-5 text-center"><i style="color: #FFE4C4" class="fas fa-hamburger fa-2x"></i>  Realizar Pedido</h3>
<%= render "form"%>
</div>
</div>

</html>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hamburgueria</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light"  style="background-color: #F4A460">
  <div class="container-fluid">
    <a class="navbar-brand text-white" href="#"><i class="fas fa-hamburger"></i>HamBurguer</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div  class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
            <%= link_to 'Bem vindos!', root_path, class: 'nav-link active navbar-brand text-white' %>
      </li>
    </ul>  
      <ul style="margin-left: auto" class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Cadastro
          </a>
          <ul class="dropdown-menu" style="background-color: #FFDEAD" aria-labelledby="navbarDropdown">
            <%= link_to 'Cadastrar Lanches', burguers_new_path, class: 'nav-link active navbar-brand' %>
            <%= link_to 'Cadastrar Bebidas', bebidas_new_path, class: 'nav-link active navbar-brand' %>
             <%= link_to 'Bebidas', bebidas_path, class: 'nav-link active navbar-brand' %>
             <%= link_to 'Lanches', burguers_path, class: 'nav-link active navbar-brand' %>
             <%= link_to 'Pedidos', contratos_path, class: 'nav-link active navbar-brand' %>
          </ul>
        </li>
         <li class="nav-item text-white dropdown text-white">
          <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Cardápio
          </a>
          <ul class="dropdown-menu" style="background-color: #FFDEAD" aria-labelledby="navbarDropdown">
            <%= link_to 'Cárdapio', cardapinho_path, class: 'nav-link active navbar-brand' %>
            <%= link_to 'Realizar Pedido', contratos_new_path, class: 'nav-link active navbar-brand' %>
          </ul>
        </li>
        <li style="margin-left: auto">
          <%= link_to "Sair", authentication_form_path , method: "delete", class: 'nav-link active navbar-brand text-white' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

    <%= yield %>
    
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HamBurguer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>